routes/web.php
<?php

use App\Http\Controllers\DashboardController;

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('dash.index');
})->name('dash');*/


Route::resource('home', HomeController::class);
Route::resource('persona', PersonaController::class);
Route::resource('vehiculo', VehiculoController::class);
Route::resource('entidadesComerciales', EntidadesComercialeController::class);
Route::resource('libretasSanitarias', LibretasSanitariaController::class);
Route::resource('licenciasReba', LicenciasRebaController::class);
Route::resource('habilitacionesComerciales', HabilitacionesComercialeController::class);

app/Models/LicenciasReba.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class LicenciasReba
 *
 * @property $id
 * @property $categoria
 * @property $fechaOtorgamiento
 * @property $fechaVencimiento
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class LicenciasReba extends Model
{

    static $rules = [
		'categoria' => '',
		'fechaOtorgamiento' => '',
		'fechaVencimiento' => '',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['categoria','fechaOtorgamiento','fechaVencimiento'];

    public function EntidadComercial()
    {
        return $this->hasOne(EntidadesComerciale::class,'licenciaReba_id','id');
    }

}

app/Http/Controllers/LicenciasRebaController.php
<?php

namespace App\Http\Controllers;

use App\Models\EntidadesComerciale;
use App\Models\LicenciasReba;
use Illuminate\Http\Request;

class LicenciasRebaController extends Controller
{

    public function index()
    {
        $licenciasReba = LicenciasReba::paginate();

        return view('licencias-reba.index', compact('licenciasReba'))
            ->with('i', (request()->input('page', 1) - 1) * $licenciasReba->perPage());
    }

    public function create()
    {
        $licenciasReba = new LicenciasReba();
        return view('licencias-reba.create', compact('licenciasReba'));
    }


    public function store(Request $request)
    {
        $licenciasReba = LicenciasReba::create($request->all());

        $entidadComercial = EntidadesComerciale::find($request->id);
        $entidadComercial->licenciaReba_id = $licenciasReba->id;
        $entidadComercial->save();

        return redirect()->route('licencias-reba.index', compact('licenciasReba'))
            ->with('success', 'Licencia Reba creada correctamente.');
    }

    public function show($id)
    {
        $licenciasReba = LicenciasReba::find($id);

        return view('licencias-reba.show', compact('licenciasReba'));
    }

    public function edit($id)
    {
        $licenciasReba = LicenciasReba::find($id);

        return view('licencias-reba.edit', compact('licenciasReba'));
    }


    public function update(Request $request, LicenciasReba $licenciasReba)
    {
//        request()->validate(LicenciasReba::$rules);


        $licenciasReba->update($request->all());

        return redirect()->route('licencias-reba.index', compact('licenciasReba'))
            ->with('success', 'Licencia Reba actualizada correctamente');
    }

    public function destroy($id)
    {
        $licenciasReba = LicenciasReba::find($id);
        $licenciasReba['borrado'] = 1;
        $licenciasReba->save();

        return redirect()->route('licencias-reba.index')
            ->with('success', 'Licencia Reba eliminada correctamente');
    }
}

resources/views/licencias-reba/create.blade.php
@extends('adminlte::page')

@section('title', 'Crear Licencia Reba')

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Licencias Reba</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('licenciasReba.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('licencias-reba.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/licencias-reba/edit.blade.php
@extends('adminlte::page')

@section('title', 'Actualizar Licencias Reba')


@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Actualizar Licencias Reba</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('licenciasReba.update', $licenciasReba->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('licencias-reba.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/licencias-reba/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        <div class="row">
            <div class="form-group col-3">
                {{ Form::label('Categoria') }}
                {{ Form::text('categoria', $licenciasReba->categoria, ['class' => 'form-control' . ($errors->has('categoria') ? ' is-invalid' : ''), 'placeholder' => 'Categoria']) }}
                {!! $errors->first('categoria', '<div class="invalid-feedback">:message</p>') !!}
            </div>
            <div class="form-group col-3">
                {{ Form::label('Fecha Otorgamiento') }}
                {{ Form::date('fechaOtorgamiento', $licenciasReba->fechaOtorgamiento, ['class' => 'form-control' . ($errors->has('fechaOtorgamiento') ? ' is-invalid' : ''), 'placeholder' => 'Fechaotorgamiento']) }}
                {!! $errors->first('fechaOtorgamiento', '<div class="invalid-feedback">:message</p>') !!}
            </div>
            <div class="form-group col-3">
                {{ Form::label('Fecha Vencimiento') }}
                {{ Form::date('fechaVencimiento', $licenciasReba->fechaVencimiento, ['class' => 'form-control' . ($errors->has('fechaVencimiento') ? ' is-invalid' : ''), 'placeholder' => 'Fechavencimiento']) }}
                {!! $errors->first('fechaVencimiento', '<div class="invalid-feedback">:message</p>') !!}
            </div>

        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</div>

resources/views/licencias-reba/index.blade.php
@extends('adminlte::page')

@section('title', 'Licencias Reba')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Licencias Reba') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('licenciasReba.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
										<th>Categoria</th>
										<th>Fecha Otorg.</th>
										<th>Fecha Venc.</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($licenciasReba as $licenciaReba)

                                        <tr>
											<td>{{ $licenciaReba->categoria }}</td>
											<td>{{ date('d-m-Y', strtotime($licenciaReba->fechaOtorgamiento )) }}</td>
											<td>{{ date('d-m-Y', strtotime($licenciaReba->fechaVencimiento  )) }}</td>

                                            <td>
                                                <form action="{{ route('licenciasReba.destroy',$licenciaReba->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('licenciasReba.show',$licenciaReba->id) }}"><i class="fa fa-fw fa-eye"></i></a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('licenciasReba.edit',$licenciaReba->id) }}"><i class="fa fa-fw fa-edit"></i></a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $licenciasReba->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/licencias-reba/show.blade.php
@extends('adminlte::page')

@section('title', 'Mostrar licencia')

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Mostrar Licencias Reba</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('licenciasRebas.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">

                        <div class="form-group">
                            <strong>Categoria:</strong>
                            {{ $licenciasReba->categoria }}
                        </div>
                        <div class="form-group">
                            <strong>Fechaotorgamiento:</strong>
                            {{ $licenciasReba->fechaOtorgamiento }}
                        </div>
                        <div class="form-group">
                            <strong>Fechavencimiento:</strong>
                            {{ $licenciasReba->fechaVencimiento }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection