routes/web.php
<?php

use App\Http\Controllers\DashboardController;

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('dash.index');
})->name('dash');*/


Route::resource('home', HomeController::class);
Route::resource('persona', PersonaController::class);
Route::resource('vehiculo', VehiculoController::class);
Route::resource('entidadesComerciales', EntidadesComercialeController::class);
Route::resource('libretasSanitarias', LibretasSanitariaController::class);
Route::resource('licenciasReba', LicenciasRebaController::class);
Route::resource('habilitacionesComerciales', HabilitacionesComercialeController::class);

app/Models/EntidadesComerciale.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class EntidadesComerciale
 *
 * @property $id
 * @property $nombre
 * @property $domicilio
 * @property $legajo
 * @property $expediente
 * @property $rubro
 * @property $tipo
 * @property $parada
 * @property $partida
 * @property $categoriaComercial_id
 * @property $habilitacionComercial_id
 * @property $licenciaReba_id
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class EntidadesComerciale extends Model
{

    static $rules = [
		'nombre' => '',
		'domicilio' => '',
		'legajo' => '',
		'expediente' => '',
		'rubro' => '',
		'tipo' => '',
		'parada' => '',
		'partida' => '',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['nombre','domicilio','legajo','expediente','rubro','tipo','parada','partida','categoriaComercial_id','habilitacionComercial_id','licenciaReba_id'];

    public function Persona_x_comercio(){

        return $this->hasMany(persona_x_comercio::class,'entidadComercial_id','id');

    }

    public function Vehiculo()
    {
        return $this->hasMany(Vehiculo::class,'entidadComercial_id','id');
    }

    public function LicenciaReba()
    {
        return $this->belongsTo(EntidadesComerciale::class,'id','licenciaReba_id');
    }

    public function HabilitacionComercial()
    {
        return $this->belongsTo(EntidadesComerciale::class,'id','habilitacionComercial_id');
    }

    public function CategoriaComercial()
    {
        return $this->belongsTo(EntidadesComerciale::class,'id','categoriaComercial_id');
    }


}

app/Http/Controllers/EntidadesComercialeController.php
<?php

namespace App\Http\Controllers;

use App\Models\CategoriasComerciale;
use App\Models\EntidadesComerciale;
use App\Models\HabilitacionesComerciale;

use App\Models\LicenciasReba;
use App\Models\Persona;
use App\Models\Vehiculo;
use Illuminate\Http\Request;

/**
 * Class EntidadesComercialeController
 * @package App\Http\Controllers
 */
class EntidadesComercialeController extends Controller
{

    public function index()
    {
        $entidadesComerciales = EntidadesComerciale::paginate();

        return view('entidades-comerciale.index', compact('entidadesComerciales'));
    }

    public function create()
    {

        $entidadesComerciale = new EntidadesComerciale();
        $vehiculo = new Vehiculo();
        $habilitacionComercial = new HabilitacionesComerciale();
        $licenciasReba = new LicenciasReba();
        $persona = Persona::all();
        $categorias = CategoriasComerciale::all();
       // dd($categorias);

        return view('entidades-comerciale.create')
                        ->with('entidadesComerciale',$entidadesComerciale)
                        ->with('vehiculos',$vehiculo)
                        ->with('habilitacionesComerciales',$habilitacionComercial)
                        ->with('licenciasReba',$licenciasReba)
                        ->with('personas',$persona)
                        ->with('categorias',$categorias);

    }


    public function store(Request $request)
    {
        //dd($request->all());
;       // request()->validate(EntidadesComerciale::$rules);
        $datos = $request->all();

        /*
          'nombre' => '',
          'domicilio' => '',
          'legajo' => '',
          'expediente' => '',
          'rubro' => '',
          'tipo' => '',
          'parada' => '',
          'partida' => '',
  */
    //    dd($datos);
        if($datos['tipo']=="comercio") {

            $entidadComercial = new EntidadesComerciale();
            $entidadComercial->nombre = $datos['nombre'];
            $entidadComercial->domicilio = $datos['domicilio'];
            $entidadComercial->legajo = $datos['legajo'];
            $entidadComercial->expediente = $datos['expediente'];
            $entidadComercial->rubro = $datos['rubro'];
            $entidadComercial->tipo = $datos['tipo'];
            $entidadComercial->parada = $datos['parada'];
            $entidadComercial->categoriaComercial_id = $datos['categoriasComerciales'];
         //   $entidadComercial->habilitacionComercial_id = $datos['partida'];
            $ok = $entidadComercial->save();
            dd($ok);
        }

        if($datos['tipo']=="remiseria") {

            $entidadComercial = new EntidadesComerciale();
            $entidadComercial->nombre = $datos['nombre'];
            $entidadComercial->domicilio = $datos['domicilio'];
            $entidadComercial->legajo = $datos['legajo'];
            $entidadComercial->expediente = $datos['expediente'];
            $entidadComercial->rubro = $datos['rubro'];
            $entidadComercial->tipo = $datos['tipo'];
            $entidadComercial->parada = $datos['parada'];
            $entidadComercial->categoriaComercial_id = $datos['categoriasComerciales'];
            //   $entidadComercial->habilitacionComercial_id = $datos['partida'];
            $ok = $entidadComercial->save();

        }

        if($ok){
            return redirect()->route('entidades-comerciale.index')
                ->with('success', 'Entidad creada correctamente.');
        }else{
            return redirect()->route('entidades-comerciale.index')
                ->with('error', 'La Entidad no se creo correctamente.');
        }

    }


    public function show($id)
    {
        $entidadesComerciale = EntidadesComerciale::find($id);

        return view('entidades-comerciale.show', compact('entidadesComerciale'));
    }

    public function edit($id)
    {
        $entidadesComerciale = EntidadesComerciale::find($id);
        $vehiculos = Vehiculo::all();
      if($entidadesComerciale->habilitacionComercial_id){
          $habilitacionComercial = HabilitacionesComerciale::find($entidadesComerciale->habilitacionComercial_id);
      }else{
          $habilitacionComercial = new HabilitacionesComerciale();
      }

        $personas = Persona::all();

            $categorias = CategoriasComerciale::all();


        if($entidadesComerciale->licenciaReba_id){
            $licenciasReba = LicenciasReba::find($entidadesComerciale->licenciaReba_id);
        }else{
            $licenciasReba = new LicenciasReba();
        }

        return view('entidades-comerciale.edit', compact('entidadesComerciale'))
            ->with('vehiculos',$vehiculos)
            ->with('habilitacionesComerciales',$habilitacionComercial)
            ->with('categorias',$categorias)
            ->with('licenciasReba',$licenciasReba)
            ->with('personas',$personas);
    }

    public function update(Request $request, EntidadesComerciale $entidadesComerciale)
    {
        //request()->validate(EntidadesComerciale::$rules);

        $entidadesComerciale->update($request->all());

        return redirect()->route('entidades-comerciale.index')
            ->with('success', 'Entidad actualizada correctamente');
    }

    public function destroy($id)
    {
        $entidadesComerciale = EntidadesComerciale::find($id);
        $entidadesComerciale['borrado'] = 1;
        $entidadesComerciale->save();

        return redirect()->route('entidades-comerciale.index')
            ->with('success', 'EntidadesComerciale deleted successfully');
    }
}

resources/views/entidades-comerciale/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">

        <div class="row" >
            <div class="form-group col-3">
                {{ Form::label('tipo') }}
                <select id="tipo" name="tipo" class="form-control" value="{{$entidadesComerciale->tipo}}" onchange="mostrar(this.value)">
                    <option value="#">Seleccione una opcion</option>
                    <option value="comercio">COMERCIO</option>
                    <option value="remiseria">REMISERIA</option>
                    <option value="taxi">TAXI</option>
                </select>
            </div>
        </div>

      <!--  <div class="row">
            <div class="form-group  col-3">
            <input type="button"  class="btn btn-warning pull-right" data-toggle="modal" data-target="#modalTitular" placeholder="Nuevo Titular" value="Nuevo Titular"></input>
        </div>
        </div>-->

        <div class="row" >

            <div class="form-group col-3" id="nombre" style="display: none;">
                {{ Form::label('Nombre') }}
                {{ Form::text('nombre', $entidadesComerciale->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            </div>

            <div class="form-group col-3" id="legajo" style="display: none;">
                {{ Form::label('Legajo') }}
                {{ Form::text('legajo', $entidadesComerciale->legajo, ['class' => 'form-control' . ($errors->has('legajo') ? ' is-invalid' : ''), 'placeholder' => 'Legajo']) }}
            </div>

            <div class="form-group col-3" id="expediente" style="display: none;">
                {{ Form::label('Expediente') }}
                {{ Form::text('expediente', $entidadesComerciale->expediente, ['class' => 'form-control' . ($errors->has('expediente') ? ' is-invalid' : ''), 'placeholder' => 'Expediente']) }}
            </div>

            <div class="form-group col-3" id="rubro" style="display: none;">
                {{ Form::label('Rubro') }}
                {{ Form::text('rubro', $entidadesComerciale->rubro, ['class' => 'form-control' . ($errors->has('rubro') ? ' is-invalid' : ''), 'placeholder' => 'Rubro']) }}
            </div>

            <div class="form-group col-3" id="domicilio" style="display: none;">
                {{ Form::label('Domicilio') }}
                {{ Form::text('domicilio', $entidadesComerciale->domicilio, ['class' => 'form-control' . ($errors->has('domicilio') ? ' is-invalid' : ''), 'placeholder' => 'Domicilio']) }}
            </div>

            <div class="form-group col-3" id="parada" style="display: none;">
                {{ Form::label('parada') }}
                {{ Form::text('parada', $entidadesComerciale->parada, ['class' => 'form-control' . ($errors->has('parada') ? ' is-invalid' : ''), 'placeholder' => 'Parada']) }}
            </div>


            <div class="form-group col-2" id="partida" style="display: none;">
                {{ Form::label('Partida') }}
                {{ Form::text('partida', $entidadesComerciale->partida, ['class' => 'form-control' . ($errors->has('partida') ? ' is-invalid' : ''), 'placeholder' => 'Partida']) }}
            </div>




            <div class="form-group col-3" id="chofer" style="display: none;">
                {{ Form::label('Chofer') }}
                <select class="form-control" name="chofer_id" id="chofer_id">
                    @foreach($personas as $chofer)
                        <option value="{{$chofer['id']}}"> {{$chofer['apellido']}}, {{$chofer['nombre']}} </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group col-2" id="categoriasComerciales" style="display: none;">
                {{ Form::label('Cat. Comercial') }}
                <select class="form-control" name="categoriasComerciales" id="categoriasComerciales">
                        @foreach($categorias as $cc)
                            <option value="{{$cc['id']}}"> {{$cc['nombre']}} </option>
                        @endforeach
                </select>
            </div>


        </div>


    </div>
</div>

    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Guardar</button>
        @if($entidadesComerciale->id && $entidadesComerciale->tipo == 'comercio')
            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalTitular">Cargar Titular/es</button>
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalReba">Licencia REBA</button>
            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalComercial">Habilitacion Com.</button>
         @endif
        @if($entidadesComerciale->id && ($entidadesComerciale->tipo == 'taxi' || $entidadesComerciale->tipo == 'remiseria'))-->
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalVehiculo">Cargar Vehiculo</button>
        <@endif

    </div>
    </div>

</div>


<!-- Modals -->
<div id="modalReba" class="modal" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Cargar Licencia REBA</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">

                    <form method="POST" action="{{ route('licenciasReba.store') }}"  role="form" enctype="multipart/form-data">
                        @csrf

                        @include('licencias-reba.form')

                    </form>

            </div>

        </div>

    </div>
</div>

<div id="modalTitular" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Nuevo Titular</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<div id="modalComercial" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">


        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Cargar Habilitacion Comercial</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ route('habilitacionesComerciales.store') }}"  role="form" enctype="multipart/form-data">
                    @csrf

                    @include('habilitaciones-comerciale.form')

                </form>
            </div>

        </div>

    </div>
</div>

<div id="modalVehiculo" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">


        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Vehículos</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">

            </div>

        </div>

    </div>

</div>
<!-- FIN MODALS -->

<script type="text/javascript" src="js/jquery.js"></script>

<script type="text/javascript">
    function mostrar(id) {

        if (id == "taxi") {
            $("#nombre").hide();
            $("#legajo").show();
            $("#expediente").show();
            $("#rubro").show();
            $("#domicilio").hide();
            $("#parada").show();
            $("#fechaInicio").show();
            $("#partida").hide();
            $("#fechaVencimiento").hide();
            $("#tipoHab").hide();
            $("#vencimientoVtv").show();
            $("#vencimientoLicencia").show();
            $("#vencimientoSeguro").show();
            $("#chofer").show();
            $("#dominio").show();
        //    $("#vehiculoContratado").show();
            $("#marca").show();
            $("#modelo").show();
           // $("#modalTitular").hide();
            $("#categoriasComerciales").hide();

        }

        if (id == "comercio") {
            $("#nombre").show();
            $("#legajo").show();
            $("#expediente").show();
            $("#rubro").show();
            $("#domicilio").show();
            $("#parada").hide();
            $("#fechaInicio").show();
            $("#partida").show();
            $("#fechaVencimiento").show();
            $("#tipoHab").show();
            $("#vencimientoVtv").hide();
            $("#vencimientoLicencia").hide();
            $("#vencimientoSeguro").hide();
            $("#chofer").hide();
            $("#dominio").hide();
           // $("#vehiculoContratado").hide();
           // $("#modalTitular").show();
            $("#categoriasComerciales").show();

        }

        if (id == "remiseria") {
            $("#nombre").show();
            $("#legajo").show();
            $("#expediente").show();
            $("#rubro").show();
            $("#domicilio").show();
            $("#parada").show();
            $("#fechaInicio").show();
            $("#partida").hide();
            $("#fechaVencimiento").hide();
            $("#tipoHab").hide();
            $("#vencimientoVtv").hide();
            $("#vencimientoLicencia").hide();
            $("#vencimientoSeguro").hide();
            $("#chofer").hide();
            $("#dominio").hide();
         //   $("#vehiculoContratado").hide();
         //   $("#modalTitular").hide();
            $("#categoriasComerciales").hide();

        }

    }
</script>

resources/views/entidades-comerciale/index.blade.php
@extends('adminlte::page')

@section('title', 'Comercios')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Entidades Comerciales') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('entidadesComerciales.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Nuevo Comercio') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="tabla" class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
										<th>Nombre</th>
										<th>Domicilio</th>
										<th>Legajo</th>
										<th>Expediente</th>
										<th>Rubro</th>
										<th>Tipo</th>
										<th>Parada</th>
										<th>Partida</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($entidadesComerciales as $entidadesComerciale)
                                        <tr>
											<td>{{ $entidadesComerciale->nombre }}</td>
											<td>{{ $entidadesComerciale->domicilio }}</td>
											<td>{{ $entidadesComerciale->legajo }}</td>
											<td>{{ $entidadesComerciale->expediente }}</td>
											<td>{{ $entidadesComerciale->rubro }}</td>
											<td>{{ $entidadesComerciale->tipo }}</td>
											<td>{{ $entidadesComerciale->parada }}</td>
											<td>{{ $entidadesComerciale->partida }}</td>

                                            <td>
                                                <form action="{{ route('entidadesComerciales.destroy',$entidadesComerciale->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('entidadesComerciales.show',$entidadesComerciale->id) }}"><i class="fa fa-fw fa-eye"></i></a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('entidadesComerciales.edit',$entidadesComerciale->id) }}"><i class="fa fa-fw fa-edit"></i></a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $entidadesComerciales->links() !!}
            </div>
        </div>
    </div>
@endsection

@section('js')

    <script type="text/javascript">
        $(document).ready(function() {
            $('#tabla').DataTable();
        } );
    </script>
@stop

resources/views/entidades-comerciale/show.blade.php
@extends('adminlte::page')

@section('title', 'Entidad Comercial')

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Ver Entidad Comercial</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('entidadesComerciales.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-3">
                                <strong>Nombre:</strong>
                                {{ $entidadesComerciale->nombre }}
                            </div>
                            <div class="form-group col-3">
                                <strong>Domicilio:</strong>
                                {{ $entidadesComerciale->domicilio }}
                            </div>
                            <div class="form-group col-3">
                                <strong>Legajo:</strong>
                                {{ $entidadesComerciale->legajo }}
                            </div>
                            <div class="form-group col-3">
                                <strong>Expediente:</strong>
                                {{ $entidadesComerciale->expediente }}
                            </div>
                            <div class="form-group col-3">
                                <strong>Rubro:</strong>
                                {{ $entidadesComerciale->rubro }}
                            </div>
                            <div class="form-group col-3">
                                <strong>Tipo:</strong>
                                {{ $entidadesComerciale->tipo }}
                            </div>
                            <div class="form-group col-3">
                                <strong>Parada:</strong>
                                {{ $entidadesComerciale->parada }}
                            </div>
                            <div class="form-group col-3">
                                <strong>Partida:</strong>
                                {{ $entidadesComerciale->partida }}
                            </div>
                         

                        </div>


                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection