routes/web.php
<?php

use App\Http\Controllers\DashboardController;

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('dash.index');
})->name('dash');*/


Route::resource('home', HomeController::class);
Route::resource('persona', PersonaController::class);
Route::resource('vehiculo', VehiculoController::class);
Route::resource('entidadesComerciales', EntidadesComercialeController::class);
Route::resource('libretasSanitarias', LibretasSanitariaController::class);
Route::resource('licenciasReba', LicenciasRebaController::class);
Route::resource('habilitacionesComerciales', HabilitacionesComercialeController::class);

app/Models/LibretasSanitaria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class LibretasSanitaria
 *
 * @property $id
 * @property $fechaVencimiento
 * @property $medicoFirmante
 * @property $persona_id
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class LibretasSanitaria extends Model
{

    static $rules = [
		'fechaVencimiento' => '',
		'medicoFirmante' => '',
		'persona_id' => '',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['fechaVencimiento','medicoFirmante','persona_id'];

    public function Persona(){

        return $this->hasOne(Persona::class,'persona_id','id');
    }

}

app/Http/Controllers/LibretasSanitariaController.php
<?php

namespace App\Http\Controllers;

use App\Models\LibretasSanitaria;
use Illuminate\Http\Request;

class LibretasSanitariaController extends Controller
{

    public function index()
    {
        $libretasSanitarias = LibretasSanitaria::paginate();

        return view('libretas-sanitaria.index', compact('libretasSanitarias'))
            ->with('i', (request()->input('page', 1) - 1) * $libretasSanitarias->perPage());
    }

    public function create()
    {
        $libretasSanitarias = new LibretasSanitaria();
        dd("llega aca");
        return view('libretas-sanitaria.create', compact('libretasSanitarias'));
    }

    public function store(Request $request)
    {
        request()->validate(LibretasSanitaria::$rules);

        $libretasSanitarias = LibretasSanitaria::create($request->all());

        return redirect()->route('libretas-sanitaria.index')
            ->with('success', 'LibretasSanitaria created successfully.');
    }

    public function show($id)
    {
        $libretasSanitarias = LibretasSanitaria::find($id);

        return view('libretas-sanitaria.show', compact('libretasSanitarias'));
    }

    public function edit($id)
    {
        $libretasSanitarias = LibretasSanitaria::find($id);

        return view('libretas-sanitaria.edit', compact('libretasSanitarias'));
    }

    public function update(Request $request, LibretasSanitaria $libretasSanitarias)
    {
        request()->validate(LibretasSanitaria::$rules);

        $libretasSanitarias->update($request->all());

        return redirect()->route('libretas-sanitarias.index')
            ->with('success', 'LibretasSanitaria updated successfully');
    }

    public function destroy($id)
    {
        $libretasSanitarias = LibretasSanitaria::find($id);
        $libretasSanitarias['borrado'] = 1;
        $libretasSanitarias->save();

        return redirect()->route('libretas-sanitarias.index')
            ->with('success', 'LibretasSanitaria deleted successfully');
    }
}

resources/views/libretas-sanitaria/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Libretas Sanitaria
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Libretas Sanitaria</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('libretasSanitarias.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('libretas-sanitaria.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/libretas-sanitaria/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Libretas Sanitaria
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Libretas Sanitaria</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('libretasSanitarias.update', $libretasSanitaria->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('libretas-sanitaria.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/libretas-sanitaria/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">

        <div class="form-group">
            {{ Form::label('fechaVencimiento') }}
            {{ Form::date('fechaVencimiento', $libretasSanitarias->fechaVencimiento, ['class' => 'form-control' . ($errors->has('fechaVencimiento') ? ' is-invalid' : ''), 'placeholder' => 'Fechavencimiento']) }}
            {!! $errors->first('fechaVencimiento', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('medicoFirmante') }}
            {{ Form::text('medicoFirmante', $libretasSanitarias->medicoFirmante, ['class' => 'form-control' . ($errors->has('medicoFirmante') ? ' is-invalid' : ''), 'placeholder' => 'Medicofirmante']) }}
            {!! $errors->first('medicoFirmante', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('persona_id') }}
            {{ Form::text('persona_id', $libretasSanitarias->persona_id, ['class' => 'form-control' . ($errors->has('persona_id') ? ' is-invalid' : ''), 'placeholder' => 'Persona Id']) }}
            {!! $errors->first('persona_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</div>

resources/views/libretas-sanitaria/index.blade.php
@extends('adminlte::page')

@section('title', 'Cargar Libreta Sanitaria')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Libretas Sanitaria') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('libretasSanitarias.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>

										<th>Fechavencimiento</th>
										<th>Medicofirmante</th>
										<th>Persona Id</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($libretasSanitarias as $libretasSanitaria)
                                        <tr>
                                            <td>{{ ++$i }}</td>

											<td>{{ $libretasSanitaria->fechaVencimiento }}</td>
											<td>{{ $libretasSanitaria->medicoFirmante }}</td>
											<td>{{ $libretasSanitaria->persona_id }}</td>

                                            <td>
                                                <form action="{{ route('libretasSanitarias.destroy',$libretasSanitaria->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('libretasSanitarias.show',$libretasSanitaria->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('libretasSanitarias.edit',$libretasSanitaria->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $libretasSanitarias->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/libretas-sanitaria/show.blade.php
@extends('adminlte::page')

@section('title', 'Libreta Sanitaria')

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Libretas Sanitaria</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('libretasSanitarias.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">

                        <div class="form-group">
                            <strong>Fechavencimiento:</strong>
                            {{ $libretasSanitaria->fechaVencimiento }}
                        </div>
                        <div class="form-group">
                            <strong>Medicofirmante:</strong>
                            {{ $libretasSanitaria->medicoFirmante }}
                        </div>
                        <div class="form-group">
                            <strong>Persona Id:</strong>
                            {{ $libretasSanitaria->persona_id }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection