routes/web.php
<?php

use App\Http\Controllers\DashboardController;

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

/*Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('dash.index');
})->name('dash');*/


Route::resource('home', HomeController::class);
Route::resource('persona', PersonaController::class);
Route::resource('vehiculo', VehiculoController::class);
Route::resource('entidadesComerciales', EntidadesComercialeController::class);
Route::resource('libretasSanitarias', LibretasSanitariaController::class);
Route::resource('licenciasReba', LicenciasRebaController::class);
Route::resource('habilitacionesComerciales', HabilitacionesComercialeController::class);

app/Models/HabilitacionesComerciale.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class HabilitacionesComerciale
 *
 * @property $id
 * @property $tipo
 * @property $fechaInicio
 * @property $fechaVencimiento
 * @property $estado
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class HabilitacionesComerciale extends Model
{

    static $rules = [
		'tipo' => '',
		'fechaInicio' => '',
		'fechaVencimiento' => '',
		'estado' => '',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['tipo','fechaInicio','fechaVencimiento','estado'];

    public function EntidadComercial(){

        return $this->hasOne(EntidadesComerciale::class,'habilitacionComercial_id','id');
    }

}

app/Http/Controllers/HabilitacionesComercialeController.php
<?php

namespace App\Http\Controllers;

use App\Models\EntidadesComerciale;
use App\Models\HabilitacionesComerciale;
use Illuminate\Http\Request;

class HabilitacionesComercialeController extends Controller
{

    public function index()
    {

        $habilitacionesComerciales = HabilitacionesComerciale::paginate();

        return view('habilitaciones-comerciale.index', compact('habilitacionesComerciales'))
            ->with('i', (request()->input('page', 1) - 1) * $habilitacionesComerciales->perPage());
    }

    public function create()
    {
        $habilitacionesComerciales = new HabilitacionesComerciale();
        return view('habilitaciones-comerciale.create', compact('habilitacionesComerciales'));
    }

    public function store(Request $request)
    {
       // dd($request->all());
        //request()->validate(HabilitacionesComerciale::$rules);

        $habilitacionesComerciales = HabilitacionesComerciale::create($request->all());

        $entidadComercial = EntidadesComerciale::find($request->id);
        $entidadComercial->licenciaReba_id = $habilitacionesComerciales->id;
        $entidadComercial->save();

        return redirect()->route('habilitaciones-comerciale.index', compact('habilitacionesComerciales'))
            ->with('habilitacionesComerciales',$habilitacionesComerciales)
            ->with('success', 'Habilitacione Comercial creada correctamente.');
    }


    public function show($id)
    {
        $habilitacionesComerciales = HabilitacionesComerciale::find($id);

        return view('habilitaciones-comerciale.show', compact('habilitacionesComerciales'));
    }

    public function edit($id)
    {
        $habilitacionesComerciales = HabilitacionesComerciale::find($id);

        return view('habilitaciones-comerciale.edit', compact('habilitacionesComerciales'));
    }

    public function update(Request $request, HabilitacionesComerciale $habilitacionesComerciale)
    {
        //request()->validate(HabilitacionesComerciale::$rules);

        $habilitacionesComerciale->update($request->all());

        return redirect()->route('habilitaciones-comerciale.index', compact('habilitacionesComerciales'))
            ->with('success', 'Habilitacion Comercial actualizada correctamente');
    }

    public function destroy($id)
    {
        $habilitacionesComerciale = HabilitacionesComerciale::find($id);
        $habilitacionesComerciale['borrado'] = 1;
        $habilitacionesComerciale->save();

        return redirect()->route('habilitaciones-comerciale.index', compact('habilitacionesComerciales'))
            ->with('success', 'Habilitacion Comercial eliminada correctamente');
    }
}

resources/views/habilitaciones-comerciale/create.blade.php
@extends('adminlte::page')

@section('title', 'Nuevo Habilitacion')

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Habilitaciones Comerciale</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('habilitacionesComerciales.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('habilitaciones-comerciale.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/habilitaciones-comerciale/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Habilitacion')

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">

                    <div class="card-header">
                        <span class="card-title">Editar Habilitacion Comercial</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('habilitacionesComerciales.update', $habilitacionesComerciales->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('habilitaciones-comerciale.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/habilitaciones-comerciale/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        <div class="row">

            <div class="form-group col-2" id="tipo" >
                {{ Form::label('Tipo Hab.') }}
                <select class="form-control" name="tipo" id="tipo">
                    <option value=""> Seleccionar </option>
                    <option value="1"> Definitivo </option>
                    <option value="0"> Transitorio </option>
                </select>
            </div>
        <div class="form-group col-3">
            {{ Form::label('fechaInicio') }}
            {{ Form::date('fechaInicio', $habilitacionesComerciales->fechaInicio, ['class' => 'form-control' . ($errors->has('fechaInicio') ? ' is-invalid' : ''), 'placeholder' => 'Fechainicio']) }}
            {!! $errors->first('fechaInicio', '<div class="invalid-feedback">:message</p>') !!}
        </div>

        <div class="form-group col-3">
            {{ Form::label('fechaVencimiento') }}
            {{ Form::date('fechaVencimiento', $habilitacionesComerciales->fechaVencimiento, ['class' => 'form-control' . ($errors->has('fechaVencimiento') ? ' is-invalid' : ''), 'placeholder' => 'Fechavencimiento']) }}
            {!! $errors->first('fechaVencimiento', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group col-3">
            {{ Form::label('estado') }}
            {{ Form::text('estado', $habilitacionesComerciales->estado, ['class' => 'form-control' . ($errors->has('estado') ? ' is-invalid' : ''), 'placeholder' => 'Estado']) }}
            {!! $errors->first('estado', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        </div>
    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</div>

resources/views/habilitaciones-comerciale/index.blade.php
@extends('adminlte::page')

@section('title', 'Habilitaciones Comerciales')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Habilitaciones Comerciale') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('habilitacionesComerciales.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Nuevo') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
										<th>Tipo</th>
										<th>Fechainicio</th>
										<th>Fechavencimiento</th>
										<th>Estado</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($habilitacionesComerciales as $habilitacionesComerciale)
                                        <tr>
                                            @if($habilitacionesComerciale->tipo==1)
}											    <td>Definitivo</td>
                                            @else
                                                <td>Transitorio</td>
                                            @endif
											<td>{{ date('d-m-Y', strtotime($habilitacionesComerciale->fechaInicio  )) }}</td>
											<td>{{ date('d-m-Y', strtotime($habilitacionesComerciale->fechaVencimiento   ))}}</td>
											<td>{{ $habilitacionesComerciale->estado }}</td>

                                            <td>

                                                <form action="{{ route('habilitacionesComerciales.destroy',$habilitacionesComerciale->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('habilitacionesComerciales.show',$habilitacionesComerciale->id) }}"><i class="fa fa-fw fa-eye"></i></a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('habilitacionesComerciales.edit',$habilitacionesComerciale->id) }}"><i class="fa fa-fw fa-edit"></i></a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $habilitacionesComerciales->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/habilitaciones-comerciale/show.blade.php
@extends('adminlte::page')

@section('title', 'Mostrar Habilitacion')

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Habilitaciones Comerciale</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('habilitacionesComerciales.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">

                        <div class="form-group">
                            <strong>Tipo:</strong>
                            {{ $habilitacionesComerciale->tipo }}
                        </div>
                        <div class="form-group">
                            <strong>Fechainicio:</strong>
                            {{ $habilitacionesComerciale->fechaInicio }}
                        </div>
                        <div class="form-group">
                            <strong>Fechavencimiento:</strong>
                            {{ $habilitacionesComerciale->fechaVencimiento }}
                        </div>
                        <div class="form-group">
                            <strong>Estado:</strong>
                            {{ $habilitacionesComerciale->estado }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection